# Generated by Django 3.1.3 on 2020-12-01 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No data provided', max_length=100)),
                ('git_url', models.CharField(default='No data provided', max_length=255)),
                ('download_dir_path', models.CharField(default='No data provided', max_length=255)),
                ('zip_project', models.CharField(default='No data provided', max_length=255)),
                ('build_script_path', models.CharField(default='No data provided', max_length=255)),
                ('unzip_project_dir', models.CharField(default='No data provided', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
