# Generated by Django 3.1.3 on 2020-11-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('git_url', models.CharField(max_length=255)),
                ('download_dir_path', models.CharField(max_length=255)),
                ('zip_project', models.CharField(max_length=255)),
                ('build_script_path', models.CharField(max_length=255)),
                ('unzip_project_dir', models.CharField(max_length=255)),
            ],
        ),
    ]
