# Generated by Django 3.1.3 on 2020-11-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_script_path',
            field=models.CharField(default='No data provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='download_dir_path',
            field=models.CharField(default='No data provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_url',
            field=models.CharField(default='No data provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='No data provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='unzip_project_dir',
            field=models.CharField(default='No data provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='zip_project',
            field=models.CharField(default='No data provided', max_length=255),
        ),
    ]
